services:
  mysql:
    env_file:
      - mysql.env
    image: mysql:latest
    container_name: yoonpage_mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./db:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
      - ./initdb.d:/docker-entrypoint-initdb.d
    platform: linux/arm64
