services:
  mysql:
    image: mysql:latest
    container_name: yoonpage_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: page1234
      MYSQL_DATABASE: yoonpage
      MYSQL_USER: page
      MYSQL_PASSWORD: page1234
      TZ: Asia/Seoul
    volumes:
      - ./db:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
      - ./initdb.d:/docker-entrypoint-initdb.d
    platform: linux/arm64
